### ISSUE TITLE
Can't find miio module, however is installed

### ISSUE THREAD

**Issue by jelmerkk** [richahl/mqttmiot-dmaker1c#1]
hi, thanks for sharing this script. I've installed miio (I can use e.g. 'miio discover' command in bash), but your script returns:

```
➜  ~ python3 fan_mqtt.py
Traceback (most recent call last):
  File "fan_mqtt.py", line 7, in <module>
    import miio
ModuleNotFoundError: No module named 'miio'
➜  ~ miio
miio <command>

Commands:
  miio configure <idOrIp>                   Control a device by invoking the
```

Any clues?

**Comment by richahl** [comment]
> hi, thanks for sharing this script. I've installed miio (I can use e.g. 'miio discover' command in bash), but your script returns:
> 
> ```
> ➜  ~ python3 fan_mqtt.py
> Traceback (most recent call last):
>   File "fan_mqtt.py", line 7, in <module>
>     import miio
> ModuleNotFoundError: No module named 'miio'
> ➜  ~ miio
> miio <command>
> 
> Commands:
>   miio configure <idOrIp>                   Control a device by invoking the
> ```
> 
> Any clues?

Have you installed python-miio? https://github.com/rytilahti/python-miio

**Comment by jelmerkk** [comment]
Of course there's another miio :)
Cool thanks, now on to the issue that my MQTT connection is timing out ...
I'll get there! 

```
connecting to broker  localhost
Something in the queue
Sending: get_properties - [{'did': '241301498', 'siid': 2, 'piid': 7}]
Got error when receiving: timed out
No valid reply! Bad request?
```
