### ISSUE TITLE
How do i run the script?

### ISSUE THREAD

**Issue by dok0001** [richahl/mqttmiot-dmaker1c#4]
Hi i have tried to get this to work for a week now.
Can you give me some tips on how i run the script 

Best regards

Daniel

**Comment by richahl** [comment]
Do you get any error messages and have you added token, DID and ip for your device in the script?

**Comment by dok0001** [comment]
No errors but where do i place the script?
And how do i execute it?

Best Regards



Den mån 6 juli 2020 17:11richahl <notifications@github.com> skrev:

**Comment by richahl** [comment]
You can place it in your home folder and execute by running 'python mqttmiot.py', if it doesn't work you can try running it in the same virtual env as home assistant.

**Comment by dok0001** [comment]
Ty man! got the script working, running it from the underlaying ubuntu system.


i tried first to run script from ssh homeassistant but didnt work. couldnt install libffi-dev libssl-dev there.
